### ISSUE TITLE
Index study time scroll bar not scrollable 

### ISSUE THREAD

**Issue by carlguo866** [solved-chinese/app#8]
In the `jiezi/templates/index.html` file, the code for scroll bar is visually done ([line 16-29](https://github.com/chenyx512/Jiezi/blob/c3c354e77670361251448804b851579fbda999aa/jiezi/templates/index.html#L16-L29)), but it is not scrollable. Is it a bug or an unimplemented function?

**Comment by georgeyjm** [comment]
It should work with the JS.

**Comment by carlguo866** [comment]
Emm... I think there might be something wrong with the implementation of the js or a missing library. Please look at it.

**Comment by georgeyjm** [comment]
I see what the problem is.
You have to place the [line referencing the JS file](https://github.com/chenyx512/Jiezi/blob/c3c354e77670361251448804b851579fbda999aa/jiezi/templates/index.html#L7) after the HTML document, otherwise the JS will load before all the HTML DOM elements, and the `$('#slider-bar')` selector won't be able to select anything.
I usually put a `{% block header %}` in the `<header>` which contains mostly CSS and JS library references, and an extra `{% block scripts %}` after the closing `</body>` which contains all the JS scripts that needs to interact with the DOM elements.

**Comment by carlguo866** [comment]
I did what u said, and it still doesn't work. Eventually, I tried using your static HTML code instead of doing the `{% extends 'base.html' %}` style and that doesn't work, too. So I guess there are most problems than just that.

**Comment by georgeyjm** [comment]
Can you give me your static HTML code, and a screenshot of the console. Thanks.

**Comment by carlguo866** [comment]
The eventual problem is that `vue.js `and` jquery.min.js `is not implemented. Changed to 
`<script src='https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.min.js' integrity='sha256-chlNFSVx3TdcQ2Xlw7SvnbLAavAQLO0Y/LBiWX04viY=' crossorigin='anonymous'></script>` 
and `<script src='https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js' integrity='sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=' crossorigin='anonymous'></script>`

The problem is fixed and the issue is closed.
